name: Upload coverage reports to Codecov
on:
  workflow_run:
    workflows: ["main"]  # The name of the first workflow
    types:
      - completed  # Trigger after the first workflow completes successfully
jobs:
  Codecoverage:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}