name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
 
    - name: Build the Docker image for user-service
      run: docker build ./backend/user-service -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest

    - name: Push image to Dockerhub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} 
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
