name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    needs: [todo-service, user-service, frontend]  # Wait for these jobs to finish successfully, so we dont push broken images

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image for user-service
      run: docker build ./backend/user-service -t ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest

    - name: Push image to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
