name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # This is a placeholder job that does nothing
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Start workflow
        run: echo "Starting Docker CI Workflow"

  build:
    runs-on: ubuntu-latest
    needs: [start, todo-service, user-service, frontend]  # Add the start job to the dependency list

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image for user-service
      run: docker build ./backend/user-service -t ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest

    - name: Push image to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest
