name: Docker Image CI

on:
  workflow_run:
    workflows: ["CI/CD Demo"]  # The name of the first workflow
    types:
      - completed  # Trigger after the first workflow completes successfully

jobs:
  # Job for todo-service Docker image
  todo-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image for todo-service
      run: docker build ./backend/todo-service -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-service:latest

    - name: Push todo-service image to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-service:latest

  # Job for user-service Docker image
  user-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image for user-service
      run: docker build ./backend/user-service -t ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest

    - name: Push user-service image to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest

  # Job for frontend Docker image
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image for frontend
      run: docker build ./frontend -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

    - name: Push frontend image to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
