name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
 
    - name: Build the Docker image for user-service
      run: docker build ./backend/user-service -t alledarw/user-service:latest

    - name: Push image to Dockerhub
      run: |
        docker push alledarw/user-service:latest
