name: CI/CD Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

# Trigger on push and pull request events
on: 
  push:
  pull_request:

jobs:
  todo-service:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Install dependencies for todo-service
        run: npm install
        working-directory: ./backend/todo-service

      - name: Build todo-service
        run: npm run build
        working-directory: ./backend/todo-service

      - name: Test todo-service
        run: npm test
        working-directory: ./backend/todo-service

  user-service:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies for user-service
        run: npm install
        working-directory: ./backend/user-service

      - name: Build user-service
        run: npm run build
        working-directory: ./backend/user-service

      - name: Test user-service
        run: npm test
        working-directory: ./backend/user-service

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies for frontend
        run: npm install
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
        env:
          CI: false # This will allow warnings to not break the build

      - name: Test frontend
        run: npm test
        working-directory: ./frontend
